### ISSUE TITLE
Feature: Bosta as a game moderator

### ISSUE THREAD

**Issue by H889761123** [mena-devs/bosta#43]
I think it will be a cool idea to introduce games to bosta, so he will act as a game moderator.
in the early 2000s I remember on IRC there was a game managed by a bot called "word scrabble (or scramble?)" 

the game's concept is simple yet it was really fun, and here's how it can be implemented:

- bosta scramble a word e.g computer => ctoepmur
- members must guess the word (maybe a hint can be provided?)
- the 1st member who guess the word will 'win' the round (score can be calculated based on time,difficulty,etc..)

many games can be introduced later (questions/answers, puzzles?,...), and if the idea took off and to avoid 'spamming' #general we can introduce channels for each game.

just a suggestion, and I thought to post it here.

**Comment by phr34ck** [comment]
that's a cool idea but as you said the problem is "spam": all interactivity will require a reply from the bot so imagine 5 active players trying to guess a word :D.

I used to play scrabble a lot on IRC when it was popular, it was a lot of fun. One of the reasons is the nature of how IRC was used (main channel and everyone talking there). I don't see it working when there is a dedicated channel just to play scrabble: you need users to be interested enough to join a channel dedicated to nothing but scrabble/games.

I'm all in for games but I'm not sure which ones will be useful/fun to play in the main channel.

**Comment by Link-** [comment]
That's a great idea, but I agree with everything @phr34ck mentioned. I don't see it happening, specifically with complaints about spam. Features that can automate / solve direct problems we are facing in the channels would be ideal.
